### ISSUE TITLE
Add a workflow to run tests on both push and pull requests.

### ISSUE THREAD

**Issue by rezmoss** [rezmoss/axios4go#12]

**Comment by rezmoss** [comment]
@Blackvote could you help

**Comment by Blackvote** [comment]
@rezmoss Hi. What kind of test? ```go test -v ```?
Sorry, what is pull request?

**Comment by rezmoss** [comment]
@Blackvote yes go test -v , you can find more detail https://github.com/rezmoss/axios4go/blob/main/makefile 
I meant the test should run on both push and pull request (GitHub Actions)
