### ISSUE TITLE
Add a workflow for releasing a new version

### ISSUE THREAD

**Issue by rezmoss** [rezmoss/axios4go#3]

**Comment by Blackvote** [comment]
What do you expect from the workflow? Are you looking for generating a changelog based on commit history? It seems like [release-please](https://github.com/googleapis/release-please-action) could be helpful in this case. I haven't set up something like this before, but I can try to assist you with configuring release-please for generating changelogs and opening PRs.

**Comment by rezmoss** [comment]
@Blackvote Sure, I think having something to make releases more organized with proper release notes would be more than enough,let me know when you’re ready to start, and I’ll assign you the task.

**Comment by Blackvote** [comment]
@rezmoss 
Here is my test [repo](https://github.com/Blackvote/release-pls-test). I was added release-please job. 
Here is [commit](https://github.com/Blackvote/release-pls-test/commit/1faa154d7f7ab0b7422bb95e048facca825c9a79) created by release-please.
Here is [PR](https://github.com/Blackvote/release-pls-test/pull/7) created by release-please.
Here is [release](https://github.com/Blackvote/release-pls-test/releases/tag/v1.1.0) created by release-please.

I try to learn how add builded artifact to release page and how work with versioning. Now i know that "fix" commit will increase path version and "feat" commit will increase minor version.

I think it would be better if I integrate release-please with artifact building in my repository, then I can provide you with an example. If this is what you are looking for, I can create the same workflow for you based on my example.

**Comment by rezmoss** [comment]
Hey @Blackvote , looks like the repo is private—I couldn't access it. You can easily fork https://github.com/rezmoss/axios4go and work on that

**Comment by rezmoss** [comment]
@Blackvote could you please look into , why failed

**Comment by Blackvote** [comment]
Sry. Repo settings -> Actions.General -> Workflow permissions. Allow "Read and write permissions" + "Allow GitHub Actions to create and approve pull requests"

**Comment by rezmoss** [comment]
@Blackvote Thx
